# 권한?
sudo: required
# we need docker
services:
    - docker
# id를 복붙할수업으니 태그사용(아무거나 가능)
before_install:
    - docker build -t khdrogba/docker-react -f Dockerfile.dev .
# run test 
# test 끝나면 exit 함(-e)
script:
    - docker run -e CI=true khdrogba/docker-react npm run test


deploy :
    # deploy 할때 이거써라 
    provider : elasticbeanstalk
    # 빈스타크에 url(region),appname(app) 에 명시되어있음
    region : "us-east-2"
    app : "docker"
    env : "Docker-env"
    # s3버킷 s3검색하면나옴
    bucket_name : "elasticbeanstalk-us-east-2-931130014731"
    bucket_path : "docker"
    on :
        branch : master
    # travis ci 에서 변수 설정c
    access_key_id : $AWS_ACCESS_KEY
    secret_access_key : "$AWS_SECRET_KEY"
